services:
  homeassistant-test:
    container_name: homeassistant-test
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - "8124:8123"
    environment:
      - TZ=Europe/Berlin
